version: 0.0
os: linux
files:
  - source: publish.zip
    destination: /home/ec2-user/games-api
hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
